<pre class='metadata'>
Title: CSS Scroll Snap: pair axis
Shortname: css-scroll-snap-pair
Level: 2
Status: w3c/UD
Repository: explainers-by-googlers/scroll-snap-type-pair
URL: https://explainers-by-googlers.github.io/scroll-snap-type-pair
Editor: David Liu, Google https://google.com, lcdavid@google.com
Abstract: Extends the scroll-snap-type property with the 'pair' keyword to enforce 2D joined-axis scroll snapping to a single target element across both axes simultaneously.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
